on:
  workflow_dispatch:
  schedule:
    # run every 4 hours
    - cron: '0 0 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Excavate
      uses: ScoopInstaller/GithubActions@main
      env:
        GITHUB_TOKEN: ${{ secrets.astrel_bucket }}
        SKIP_UPDATED: '1'
